// plan_sites.js — GENERATED by scripts/plan_sites.py. Do not hand edit.
//
// Stage 2 of the true-scale plan (DECISIONS.md call 54). Each entry says where a
// precinct stands today (`was`), where research/plan.json puts it (`centre`), and the
// rigid `shift` between the two. HPWorldScene wraps each precinct's builders in a
// `_placeAt(dx, dz, 0, ...)` using that shift, so no coordinate inside any builder
// has to move — which is the whole point, and the answer to HANDOVER.md §4.3.
//
// `greenfield` means the world had no such precinct until stage 2. Its builder is
// written in the precinct's OWN frame, origin at its centre, and the shift IS the
// plan centre — which is why `was` reads [0, 0] for those.
//
// The itinerary is 9,184 m long and 1,850 m at its widest.

export const PLAN_ANCHOR = 104.0;   // world z of the front of the porch, the plan's origin

// Stage 1's factor. It is not history: it is the frame every existing precinct's
// INTERIOR is authored in, because stage 1 multiplied the world by four and stage 2
// deliberately did not touch a single interior coordinate. Anything still written in
// the original cramped coordinates - the dream mode's paths, the meadow's clearance
// map - reaches the world through `toWorld`, which applies both moves in order.
export const SPREAD = 4;

// A point written in the ORIGINAL (pre-2026-09-17) coordinates, in world metres.
// `key` is the precinct the point belongs to, and the two moves are x4 then shift.
export function toWorld(key, x, z) {
  const s = PLAN_SITES[key];
  if (!s) throw new Error(`toWorld: no precinct named "${key}"`);
  return [x * SPREAD + s.shift[0], z * SPREAD + s.shift[1]];
}

export const PLAN_EXTENT = {
  zSouth: 3273.4, zNorth: -5910.4, widthMax: 1850.0, length: 9183.8,
};

export const PLAN_SITES = {
  // plain — The Spacious Plain (ch. I)
  //   from plain
  plain: { centre: [0.0, 2903.4], was: [0.0, 1792.0], shift: [0.0, 1111.4],
    width: 1110.0, depth: 740.0, zSouth: 3273.4, zNorth: 2533.4, greenfield: false, fixed: false, sized: 'ours' },
  // wood — The Dark Wood (ch. I)
  //   anchored on the WOOD box centre (z0 1192.5, z1 1387.5), not the station inside it
  wood: { centre: [0.0, 2225.9], was: [0.0, 1290.0], shift: [0.0, 935.9],
    width: 740.0, depth: 555.0, zSouth: 2503.4, zNorth: 1948.4, greenfield: false, fixed: false, sized: 'ours' },
  // spring — The Spring and the Stream (ch. I)
  //   greenfield
  spring: { centre: [-260.0, 2225.9], was: [0.0, 0.0], shift: [-260.0, 2225.9],
    width: 370.0, depth: 120.0, zSouth: 2285.9, zNorth: 2165.9, greenfield: true, fixed: false, sized: 'ours' },
  // great_oak — The Great Oak in the Green Mead (ch. I)
  //   from great_oak
  great_oak: { centre: [90.0, 1688.4], was: [36.0, 712.0], shift: [0.0, 976.4],
    width: 370.0, depth: 370.0, zSouth: 1873.4, zNorth: 1503.4, greenfield: false, fixed: false, sized: 'ours' },
  // palm_plain — The Palm and the Wolf (ch. II)
  //   from palm_plain
  palm_plain: { centre: [-60.0, 1288.4], was: [-24.0, 564.0], shift: [0.0, 724.4],
    width: 555.0, depth: 370.0, zSouth: 1473.4, zNorth: 1103.4, greenfield: false, fixed: false, sized: 'ours' },
  // valley — The Valley of the Approach (ch. II–III)
  //   FIXED — its north edge abuts the court at 148.4 already; stage 2 lengthens it south
  valley: { centre: [0.0, 610.9], was: [0.0, 610.9], shift: [0.0, 0.0],
    width: 1139.6, depth: 925.0, zSouth: 1073.4, zNorth: 148.4, greenfield: false, fixed: true, sized: 'stated+ours' },
  // piazza — The Court before the Porch (ch. III)
  //   FIXED — PIAZZA.z0 = 104 and side = 44.4 are the book's own numbers and already hold
  piazza: { centre: [0.0, 126.2], was: [0.0, 126.2], shift: [0.0, 0.0],
    width: 1139.6, depth: 44.4, zSouth: 148.4, zNorth: 104.0, greenfield: false, fixed: true, sized: 'stated' },
  // pyramid — The Pyramid-Portal (ch. III–IV)
  //   FIXED — the porch front is the plan origin and is already at z = 104; stage 2 grows this precinct northward rather than moving it
  pyramid: { centre: [0.0, -465.8], was: [0.0, -465.8], shift: [0.0, 0.0],
    width: 1139.6, depth: 1139.6, zSouth: 104.0, zNorth: -1035.6, greenfield: false, fixed: true, sized: 'stated' },
  // wooded_country — The Wooded Country and the Bridge (ch. VI)
  //   from fields
  wooded_country: { centre: [-120.0, -1435.6], was: [-96.0, 256.0], shift: [-24.0, -1691.6],
    width: 925.0, depth: 740.0, zSouth: -1065.6, zNorth: -1805.6, greenfield: false, fixed: false, sized: 'ours' },
  // fountain_house — The Octagonal Fountain and the Bath (ch. VI–VII)
  //   greenfield
  fountain_house: { centre: [60.0, -1435.6], was: [0.0, 0.0], shift: [60.0, -1435.6],
    width: 120.0, depth: 120.0, zSouth: -1375.6, zNorth: -1495.6, greenfield: true, fixed: false, sized: 'ours' },
  // cypress_avenue — The Cypress Avenue (ch. VIII)
  //   greenfield
  cypress_avenue: { centre: [0.0, -2205.6], was: [0.0, 0.0], shift: [0.0, -2205.6],
    width: 40.0, depth: 740.0, zSouth: -1835.6, zNorth: -2575.6, greenfield: true, fixed: false, sized: 'stated' },
  // enclosure — The Green Enclosure (ch. VIII)
  //   greenfield
  enclosure: { centre: [0.0, -2620.0], was: [0.0, 0.0], shift: [0.0, -2620.0],
    width: 88.8, depth: 88.8, zSouth: -2575.6, zNorth: -2664.4, greenfield: true, fixed: false, sized: 'stated' },
  // palace — Queen Eleuterylida's Palace (ch. VIII–XI)
  //   from court, planetary_palace, chess, artificial, quinta_essentia
  palace: { centre: [0.0, -2803.2], was: [-56.9, 31.8], shift: [0.0, -2835.0],
    width: 462.5, depth: 277.5, zSouth: -2664.4, zNorth: -2941.9, greenfield: false, fixed: false, sized: 'stated+ours' },
  // polia_garden — Polia's Ivied Garden (ch. XII–XIII)
  //   from polia
  polia_garden: { centre: [0.0, -3042.4], was: [58.0, 94.0], shift: [0.0, -3136.4],
    width: 141.0, depth: 141.0, zSouth: -2971.9, zNorth: -3112.9, greenfield: false, fixed: false, sized: 'stated' },
  // three_doors — The Three Doors (ch. XIII)
  //   from three_doors
  three_doors: { centre: [0.0, -3280.4], was: [0.0, 84.0], shift: [0.0, -3364.4],
    width: 277.5, depth: 185.0, zSouth: -3187.9, zNorth: -3372.9, greenfield: false, fixed: false, sized: 'ours' },
  // triumphs — The Four Triumphs (ch. XIV)
  //   from triumphs
  triumphs: { centre: [0.0, -3587.9], was: [22.0, -18.0], shift: [0.0, -3569.9],
    width: 277.5, depth: 370.0, zSouth: -3402.9, zNorth: -3772.9, greenfield: false, fixed: false, sized: 'ours' },
  // vertumnus — Vertumnus, Pomona and the Rite of Priapus (ch. XV–XVI)
  //   from priapus
  vertumnus: { centre: [150.0, -3895.4], was: [176.0, -48.0], shift: [0.0, -3847.4],
    width: 277.5, depth: 185.0, zSouth: -3802.9, zNorth: -3987.9, greenfield: false, fixed: false, sized: 'stated+ours' },
  // venus_temple — The Temple of Venus Physizoa (ch. XVII–XVIII)
  //   from venus_temple
  venus_temple: { centre: [-200.0, -4110.4], was: [-120.0, -48.0], shift: [0.0, -4062.4],
    width: 185.0, depth: 185.0, zSouth: -4017.9, zNorth: -4202.9, greenfield: false, fixed: false, sized: 'ours' },
  // polyandrion — The Polyandrion (ch. XIX)
  //   from polyandrion
  polyandrion: { centre: [230.0, -4325.4], was: [92.0, -88.0], shift: [0.0, -4237.4],
    width: 185.0, depth: 185.0, zSouth: -4232.9, zNorth: -4417.9, greenfield: false, fixed: false, sized: 'ours' },
  // shore — The Shore, and Cupid's Boat (ch. XX)
  //   from cythera
  shore: { centre: [0.0, -4494.1], was: [0.0, -132.0], shift: [0.0, -4362.1],
    width: 740.0, depth: 92.5, zSouth: -4447.9, zNorth: -4540.4, greenfield: false, fixed: false, sized: 'ours' },
  // crossing — The Crossing (ch. XX)
  //   greenfield
  crossing: { centre: [0.0, -4910.4], was: [0.0, 0.0], shift: [0.0, -4910.4],
    width: 1850.0, depth: 740.0, zSouth: -4540.4, zNorth: -5280.4, greenfield: true, fixed: false, sized: 'ours' },
  // cythera — The Island of Cythera (ch. XXI–XXIV)
  //   anchored on the isle's own centre CZ in _buildCytheraIsle, which everything is radial from
  cythera: { centre: [0.0, -5595.4], was: [12.2, -600.0], shift: [0.0, -4995.4],
    width: 630.0, depth: 630.0, zSouth: -5280.4, zNorth: -5910.4, greenfield: false, fixed: false, sized: 'ours' },
  // treviso — Treviso — Polia's City (ch. XXV–XXXVIII)
  //   from book_two
  treviso: { centre: [1400.0, -496.0], was: [176.0, 128.0], shift: [1224.0, -624.0],
    width: 740.0, depth: 740.0, zSouth: null, zNorth: null, greenfield: false, fixed: false, sized: 'ours' },
};

// The shift for a precinct, as [dx, dz]. Unknown keys are a programming error and
// throw rather than silently returning zero — a precinct that quietly does not move
// is exactly the failure this whole file exists to prevent.
export function shiftOf(key) {
  const s = PLAN_SITES[key];
  if (!s) throw new Error(`plan_sites: no precinct named "${key}"`);
  return s.shift;
}
