#!/usr/bin/env python3
# coverage_report.py — render research/coverage.json as COVERAGE.md.
#
# COVERAGE.md is GENERATED. Never hand-edit it; edit the ledger and re-run:
#
#   python scripts/coverage_seed.py && python scripts/coverage_report.py
#
# The report leads with the two queues that matter, in this order:
#   1. the RESEARCH gap — chapters nobody has enumerated. This is the queue that
#      was empty-by-omission when the vaults under the pyramid went unbuilt for
#      months: no plate existed for them, so no plate-driven check could see it,
#      and no one had read chapter V against the world.
#   2. the BUILD gap — features the book has and the world does not.
import io, json, os, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(ROOT, "research", "coverage.json")
OUT = os.path.join(ROOT, "COVERAGE.md")

MARK = {"built": "✅", "partial": "◐", "unbuilt": "○", "declined": "—", "unknown": "?"}


def main():
    d = json.load(io.open(LEDGER, encoding="utf-8"))
    chs = d["chapters"]
    res = collections.Counter(c["research"]["status"] for c in chs)
    feats = [(c, f) for c in chs for f in c["features"]]
    st = collections.Counter(f["status"] for _, f in feats)
    plates_attached = sum(len(c["plates"]) for c in chs)

    L = []
    w = L.append
    w("# COVERAGE — what the book has, and what the world has\n")
    w("*Generated by `scripts/coverage_report.py` from `research/coverage.json`. "
      "**Do not hand-edit this file** — edit the ledger and re-run. "
      "The workflow that fills it is [`HPTOTOURPIPELINE.md`](HPTOTOURPIPELINE.md).*\n")
    w(f"Ledger generated **{d['generated']}**. "
      f"{len(chs)} chapters · {plates_attached} plates attached to a chapter · "
      f"{len(d['plates_not_attached_to_a_chapter'])} not yet attached.\n")

    w("## Where the gaps are\n")
    w("| | |")
    w("|---|---|")
    w(f"| Chapters **enumerated** (a feature list exists) | **{res['enumerated']} of {len(chs)}** |")
    w(f"| Chapters **partial** (tour notes only, no feature list) | {res['partial']} |")
    w(f"| Chapters **unread** | {res['unread']} |")
    w(f"| Features **built** | {st['built']} |")
    w(f"| Features **partial** | {st['partial']} |")
    w(f"| Features **unbuilt** | **{st['unbuilt']}** |")
    w(f"| Features **declined** (on purpose, with a reason) | {st['declined']} |")
    w("")
    w("> The first row is the one that matters. A chapter that is not enumerated cannot "
      "have a gap, because nobody has looked. That is exactly how the vaults under the "
      "pyramid stayed unbuilt: they have **no woodcut**, so every plate-driven check "
      "passed them, and no one had read chapter V against the world.\n")

    # ── the research queue ────────────────────────────────────────────────
    w("## 1. The research queue — chapters nobody has enumerated\n")
    w("Work these with [`RECIPES/research-a-chapter.md`](RECIPES/research-a-chapter.md) "
      "or `/research-chapter <numeral>`.\n")
    w("| Ch. | Book | 1499 pages | Plates | Tour stops | Read it in |")
    w("|---|---|---|---|---|---|")
    for c in chs:
        if c["research"]["status"] == "enumerated":
            continue
        pr = f"{c['pages_1499'][0]}–{c['pages_1499'][1]}" if c["pages_1499"] else "—"
        stops = ", ".join(s["station"] for s in c["tour_stops"]) or "—"
        w(f"| **{c['id']}** | {c['book']} | {pr} | {len(c['plates'])} | {stops} | "
          f"{c['text_source']['edition']} |")
    w("")

    # ── the build queue ───────────────────────────────────────────────────
    w("## 2. The build queue — in the book, not in the world\n")
    unb = [(c, f) for c, f in feats if f["status"] in ("unbuilt", "partial")]
    if not unb:
        w("*Nothing outstanding in the chapters enumerated so far.*\n")
    else:
        w("| Ch. | Feature | Kind | Status | Source | Note |")
        w("|---|---|---|---|---|---|")
        for c, f in unb:
            w(f"| {c['id']} | **{f['name']}** | {f['kind']} | {MARK[f['status']]} {f['status']} | "
              f"{f['source']} | {f.get('note','')} |")
        w("")

    # ── the whole ledger ──────────────────────────────────────────────────
    w("## 3. Chapter by chapter\n")
    for c in chs:
        pr = f"1499 pp. {c['pages_1499'][0]}–{c['pages_1499'][1]}" if c["pages_1499"] else "page range not yet fixed"
        w(f"### Chapter {c['id']}  · Book {c['book']} · {pr}\n")
        w(f"*Research: **{c['research']['status']}**. {c['research'].get('note','')}*  ")
        w(f"*Text: {c['text_source']['edition']} — `{c['text_source']['file']}`*  ")
        if c["tour_stops"]:
            w("*Tour: " + "; ".join(f"{s['title']} ({s['station']}, {s['notes']} notes)"
                                    for s in c["tour_stops"]) + "*  ")
        if c["plates"]:
            w(f"*Plates: " + ", ".join(f"#{p['plate']}" for p in c["plates"]) + "*  ")
        w("")
        if c["features"]:
            w("| | Feature | Kind | Built as | Source |")
            w("|---|---|---|---|---|")
            for f in c["features"]:
                built = f"`{f['built_as']}`" if f.get("built_as") else "—"
                note = f"<br>*{f['note']}*" if f.get("note") else ""
                w(f"| {MARK[f['status']]} | {f['name']}{note} | {f['kind']} | {built} | {f['source']} |")
            w("")
        else:
            w("*No features enumerated yet.*\n")

    if d["plates_not_attached_to_a_chapter"]:
        w("## 4. Plates not yet attached to a chapter\n")
        w("These are the Book I plates; their chapters have no fixed 1499 page range because "
          "chapters I–XVI exist for us only in Dallington, whose page numbers are his own. "
          "Attaching them is part of researching those chapters.\n")
        w("| Plate | Section | 1499 p. | Description |")
        w("|---|---|---|---|")
        for p in d["plates_not_attached_to_a_chapter"]:
            w(f"| #{p['plate']} | {p['section']} | {p['page_1499'] or '—'} | {p['description']} |")
        w("")

    io.open(OUT, "w", encoding="utf-8", newline="").write("\n".join(L))
    print(f"wrote {os.path.relpath(OUT, ROOT)} — {res['enumerated']}/{len(chs)} chapters enumerated, "
          f"{st['unbuilt']} unbuilt features")


if __name__ == "__main__":
    main()
