#!/usr/bin/env python3
"""doc_costs.py — stamp every root document with what it costs to read, and
regenerate the cost table in ROUTER.md.

    python scripts/doc_costs.py

Why. Measured 2026-09-08: 62 root .md files, ~206 000 tokens. ROUTER.md routes a
task to its documents by SUBJECT, so an agent can find the right file but has no
way to know it cannot afford it — and ROUTER.md itself costs 5 400 tokens. This
puts the price on the label.

The estimate is chars/4, which is close enough for English prose and is the same
arithmetic used throughout ENGINEERING.md §2. It is deliberately not a real
tokeniser: the number is for deciding whether to open a file, and being wrong by
ten per cent never changes that decision.

Run it after any substantial documentation change. The stamps and the table are
GENERATED; edit READ_FOR below, not the output.
"""
import io, os, glob, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STAMP = re.compile(r"^<!--\s*tokens:.*?-->\s*\n", re.S)
BEGIN = "<!-- BEGIN doc-costs (generated by scripts/doc_costs.py) -->"
END = "<!-- END doc-costs -->"

# What a document is for, in a few words. Only the ones an agent is routed to
# need an entry; the rest are stamped with a cost and left alone. Keep these
# short — they are a label, not a summary.
READ_FOR = {
    "ROUTER.md":            "the task table; read this first, then two or three files",
    "CLAUDE.md":            "the seven rules (auto-loaded; you already have it)",
    "ENGINEERING.md":       "how this project is built, measured and handed over",
    "TICKETS.md":           "the engineering queue (generated)",
    "NEXTSTEPS.md":         "Ted's standing asks, in his words",
    "DECISIONS.md":         "the index of every directional call",
    "COVERAGE.md":          "what the book has that the world does not (generated)",
    "DRAWCALLS.md":         "why the world costs what it costs, and the merge we declined",
    "ROLLING.md":           "every variable in Roll Up and which one to turn",
    "HUMANOIDS.md":         "why the figures look wrong; poses, canon, registers",
    "ANIMALS.md":           "the bestiary, and §4 for why the beasts read badly",
    "DIMENSIONS.md":        "how big anything is, in metres, with sources",
    "DIRECTIONS.md":        "where things stand in relation to each other; the compass",
    "WOODS.md":             "the dark wood: species, density, light",
    "SOURCES.md":           "the corpus map, and which scholar to read per asset",
    "15scholars.md":        "what each scholar will and will not support",
    "GARDENS.md":           "the island's rings, terraces, parterres, topiary",
    "PLEASURES.md":         "what a Renaissance garden was for",
    "ARCHITECTURE.md":      "orders, members, the portal, the temples, the theatre",
    "PLANTS.md":            "species, planting, the herb-set inscriptions",
    "RENDERING.md":         "how the world is drawn; aerial perspective, the 1499 palette",
    "DESIGN.md":            "the lens system and the game's shape",
    "DEPLOY_STATE.md":      "the host, the version chain, and the deploy gotchas",
    "MODES.md":             "the five modes, and what every addition owes each",
    "ROLLMODE.md":          "the design brief behind Roll Up",
    "MASONRY.md":           "how a wall becomes stones",
    "LITTER.md":            "the 8 976 objects on the floors",
    "PROCESSIONS.md":       "the triumphs, cars, teams, liveries",
    "NYMPHS.md":            "who the figures are",
    "CHARACTERS.md":        "the named cast",
    "COMPLETE_BRIEFING.md": "SUPERSEDED — June 2026 two-world planning",
    "TWO_WORLDS_FRAMEWORK.md": "SUPERSEDED — June 2026 two-world planning",
    "HPTOTOURPIPELINE.md":  "corpus in, game out: the research-to-build route",
}


# Files written by another script. Stamping them is pointless — the next
# `coverage_report.py` or `tickets_report.py` run overwrites the file and the
# stamp with it — and worse, it would look like a stamp that had gone stale. They
# still appear in the table below with their cost; they just carry no header.
GENERATED = {"COVERAGE.md", "TICKETS.md"}


def est(path):
    return os.path.getsize(path) // 4


def stamp_all():
    out = []
    for f in sorted(glob.glob(os.path.join(ROOT, "*.md"))):
        name = os.path.basename(f)
        s = io.open(f, encoding="utf-8").read()
        s = STAMP.sub("", s, count=1)          # drop the old stamp, if any
        why = READ_FOR.get(name, "")
        if name in GENERATED:
            io.open(f, "w", encoding="utf-8").write(s)   # leave it as its script wrote it
            out.append((name, est(f), (why + " · generated").strip(" ·")))
            continue
        n = (os.path.getsize(f) // 4)
        line = f"<!-- tokens: ~{n:,} -->\n" if not why else f"<!-- tokens: ~{n:,} · read for: {why} -->\n"
        io.open(f, "w", encoding="utf-8").write(line + s)
        out.append((name, est(f), why))
    return sorted(out, key=lambda r: -r[1])


def write_table(rows):
    p = os.path.join(ROOT, "ROUTER.md")
    s = io.open(p, encoding="utf-8").read()
    total = sum(r[1] for r in rows)
    body = [BEGIN,
            "",
            "## What each document costs",
            "",
            f"*Generated by `scripts/doc_costs.py`. **{len(rows)} files in the root, "
            f"~{total:,} tokens all told** — which is why this file exists and why you should "
            "open two or three of them and not twenty. The estimate is chars/4; it is for "
            "deciding whether you can afford a file, and being wrong by ten per cent never "
            "changes that. Re-run the script after any substantial documentation change.*",
            "",
            "| tokens | file | read for |",
            "|---:|---|---|"]
    for name, n, why in rows:
        body.append(f"| ~{n:,} | `{name}` | {why} |")
    body += ["", END]
    block = "\n".join(body)
    if BEGIN in s:
        s = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, s, flags=re.S)
    else:
        s = s.rstrip() + "\n\n---\n\n" + block + "\n"
    io.open(p, "w", encoding="utf-8").write(s)
    return total


if __name__ == "__main__":
    rows = stamp_all()
    rows = stamp_all()      # twice: the first pass changes every file's size
    total = write_table(rows)
    print(f"stamped {len(rows)} files, ~{total:,} tokens total")
    for name, n, why in rows[:8]:
        print(f"  ~{n:6,}  {name}")
