#!/usr/bin/env python3
# tickets_report.py - render research/tickets.json as TICKETS.md.
#
# TICKETS.md is GENERATED. Never hand-edit it; edit the ledger and re-run:
#
#   python scripts/tickets_report.py
#
# The report leads with the queue an agent can actually pick up - open tickets
# whose acceptance criterion is machine-checkable and whose blocker is nobody -
# and keeps three things visibly separate from it:
#
#   * QUESTIONS, which are blocked on a directional call that is Ted's;
#   * BLOCKED, which are blocked on another ticket;
#   * DONE, kept because an acceptance criterion that has been met once is the
#     regression test for the next change.
#
# That separation is the point. A queue that mixes "go and do this" with "ask
# Ted" reads as longer than it is, and the asking never happens.
import io, json, os, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(ROOT, "research", "tickets.json")
OUT = os.path.join(ROOT, "TICKETS.md")

MARK = {"open": "○", "doing": "◐", "blocked": "▨", "question": "?",
        "declined": "—", "done": "✅"}
ORDER = ["open", "doing", "blocked", "question", "declined", "done"]


def render(t):
    """One ticket, as a block. Every field that exists is shown; none is invented."""
    L = []
    w = L.append
    w("### `%s` — %s\n" % (t["id"], t["title"]))
    w("**%s %s** · %s · priority %s · %s"
      % (MARK.get(t["status"], "?"), t["status"], t["kind"], t.get("priority", "-"),
         t.get("role", "unassigned")))
    if t.get("closed"):
        w(" · opened %s, closed %s" % (t["opened"], t["closed"]))
    else:
        w(" · opened %s" % t["opened"])
    w("\n")
    w("**Evidence.** %s\n" % t["evidence"])
    w("**Acceptance.** %s\n" % t["acceptance"])
    if t.get("blocked_on"):
        w("**Blocked on.** %s\n" % t["blocked_on"])
    if t.get("risk"):
        w("**Risk.** %s\n" % t["risk"])
    if t.get("resolution"):
        w("**Resolution.** %s\n" % t["resolution"])
    if t.get("files"):
        w("**Files.** %s\n" % " · ".join("`%s`" % f for f in t["files"]))
    if t.get("refs"):
        w("**See.** %s\n" % " · ".join(t["refs"]))
    return "\n".join(L)


def main():
    d = json.load(io.open(LEDGER, encoding="utf-8"))
    ts = d["tickets"]
    by = collections.defaultdict(list)
    for t in ts:
        by[t["status"]].append(t)
    for k in by:
        by[k].sort(key=lambda t: (t.get("priority", 9), t["id"]))

    counts = collections.Counter(t["status"] for t in ts)
    kinds = collections.Counter(t["kind"] for t in ts)

    L = []
    w = L.append
    w("# TICKETS — the engineering queue\n")
    w("*Generated by `scripts/tickets_report.py` from `research/tickets.json`. "
      "**Do not hand-edit this file** — edit the ledger and re-run.*\n")
    w("*What belongs here and what does not: `NEXTSTEPS.md` is Ted's voice, quoted, "
      "and stays prose. `DECISIONS.md` is the ledger of directional calls. This is "
      "defects, debt, performance and infrastructure, and **every ticket carries an "
      "acceptance criterion a machine could check**. If one cannot be written, the item "
      "is a design question and belongs in `DECISIONS.md` as a question for Ted — see "
      "`ENGINEERING.md` §3.*\n")
    w("---\n")
    w("**%d tickets** — %s. By kind: %s.\n"
      % (len(ts),
         ", ".join("%d %s" % (counts[s], s) for s in ORDER if counts[s]),
         ", ".join("%d %s" % (n, k) for k, n in kinds.most_common())))
    w("---\n")

    heads = [
        ("open", "## The queue — pick from the top",
         "Nothing blocks these but doing them."),
        ("doing", "## In hand", ""),
        ("blocked", "## Blocked on another ticket",
         "Doing these first would make the measured problem worse."),
        ("question", "## Questions for Ted",
         "Blocked on a directional call. **An agent must not decide these.**"),
        ("declined", "## Declined — measured, put to Ted, and deliberately not done",
         "**Do not re-propose these.** They are here so the next agent finds the answer "
         "instead of re-deriving the question. A declined ticket keeps its evidence: the "
         "measurement was right, the work was still not wanted."),
        ("done", "## Done — kept as regression tests",
         "An acceptance criterion that has been met once is the test for the next change."),
    ]
    for status, head, blurb in heads:
        if not by[status]:
            continue
        w(head + "\n")
        if blurb:
            w("*%s*\n" % blurb)
        for t in by[status]:
            w(render(t))
            w("")
        w("---\n")

    io.open(OUT, "w", encoding="utf-8").write("\n".join(L).rstrip() + "\n")
    print("wrote %s — %d tickets (%s)"
          % (os.path.relpath(OUT, ROOT), len(ts),
             ", ".join("%d %s" % (counts[s], s) for s in ORDER if counts[s])))


if __name__ == "__main__":
    main()
